name: Build caddy

on:
  workflow_dispatch:

  release:
    types: 
      - 'prereleased' 
      - 'published' 
      - 'released'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:  
        - {
            name: "linux-amd64",
            GOARCH: amd64,
            GOOS: linux,
            release: true
          }
        - {
            name: "linux-arm64",
            GOARCH: arm64,
            GOOS: linux,
            release: true
          }
        - {
            name: "linux-armv7",
            GOARCH: arm,
            GOARM: 5,
            GOOS: linux,
            release: true
          }
     

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        check-latest: true
    - name: Set variables
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get -y  install curl jq  
        echo  "VERSION=$(curl -sL https://api.github.com/repos/caddyserver/caddy/releases/latest | jq -r ".tag_name")" >> $GITHUB_ENV  

    - name: Install xcaddy
      run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
    
    - name: Build caddy
      run: |
        mkdir release-tmp
        export GOARCH=${{ matrix.config.GOARCH }} 
        export GOOS=${{ matrix.config.GOOS }} 
        ~/go/bin/xcaddy build \
          --with github.com/caddyserver/forwardproxy@caddy2=github.com/klzgrad/forwardproxy@naive \
          --with github.com/caddy-dns/cloudflare \
          --with github.com/xh116/caddy-trojan \
          --with github.com/mholt/caddy-webdav \
          --output ./release-tmp/caddy

    
    - name: Calculate Hash
      run: |
        cd ./release-tmp || exit 1
        sha256sum * > sha256
 
    
    - name: Generate tar for other platform
      run: |
        mkdir release-ready
        cd ./release-tmp
        tar -zcvf ../release-ready/caddy-${{ matrix.config.name }}.tar.gz *

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: caddy-${{ github.sha }}-${{ matrix.config.name }}
        path: ./release-ready/*
        
         
    - name: Upload to GitHub Release for other platform
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./release-ready/caddy-${{ matrix.config.name }}.tar.gz
        tag: ${{ github.ref }}
        overwrite: true
