name: Build
on:
  push:
    branches: [main]
    paths-ignore: [README.md]
  release:
    types: [published]
defaults:
  run:
    shell: bash
jobs:
  build_caddy:
    runs-on: ubuntu-22.04
    env:
      BUNDLE: caddy
    steps:
      - uses: actions/checkout@v3
      - name: Set variables
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get -y  install curl jq  
          echo  "VERSION=$(curl -sL https://api.github.com/repos/caddyserver/caddy/releases/latest | jq -r ".tag_name")" >> $GITHUB_ENV  

      - uses: actions/setup-go@v3
        with:
          go-version: ^1.18.1

      - name: build caddy 
      - run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest  
      - run: cd ~/go && ls &&\ 
             ~/go/xcaddy  ${{ env.VERSION }} build \
                --with github.com/caddyserver/forwardproxy@caddy2=github.com/klzgrad/forwardproxy@naive \
                --with github.com/caddy-dns/cloudflare \
                --with github.com/xh116/caddy-trojan \
                --with github.com/mholt/caddy-webdav

      - name: Pack caddy assets
        run: |
          mkdir ${{ env.BUNDLE }}
          cp caddy LICENSE README.md ${{ env.BUNDLE }}
          tar cJf ${{ env.BUNDLE }}.tar.xz ${{ env.BUNDLE }}
          openssl sha256 ./caddy >sha256sum.txt
          echo "SHA256SUM=$(cut -d' ' -f2 sha256sum.txt)" >>$GITHUB_ENV
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.BUNDLE }}.tar.xz caddy executable sha256 ${{ env.SHA256SUM }}
          path: sha256sum.txt
      - name: Upload caddy assets
        if: ${{ github.event_name == 'release' }}
        run: hub release edit -a ${{ env.BUNDLE }}.tar.xz -m "" "${GITHUB_REF##*/}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
